dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: D3KZpfvo+9WfGhrVyG0B8XqwxqOD7ZaVfKzMnw1YDk/o7qX89Mg2uQmi9Rl97oEB0ZTF56XVzQVlPxteyz5NooE5Qz3V8Notcy9Z519viDLDV/Hx+sTnMTbRg8+M6TQsiZcDLCkNWvl3VUP40nhLU20YxXUyrLJzZ+P+NTxuGKmmpQZSeIFDvkdmF3d9aiB6/tbIjJr26mg8ddU95c4DudpvdV16G1bWGJipc8lMgNeRa+xgGSApQiEh/TcAwUxQilztxP82MewnfagCFXP4bxiR1tYtjnr1kraHCqLg7+VoPZ+QLKVUZ1/q7XIf7x+jMvExKjAsZnWpn4YxVDl+qhkUNtFTrMQoo00MHtc2UhNF1+F3x01TCgL1oqzNR+0rIAUbTucAR9cXCTizQxPi91p/gy4xH0aIH6C8PyEvfO8aLxG2J+t6MMAJIUWHSEoMpf5MvsNlNpEf5x3owaAWa8nARlkmrt1kQrcTQ+vOJsz8iOWos7PcC+ocNx9NrPRSUZSK3prqdSktfg0CJgmtKkRL4M6kdhEAXtcsCGc2P56b8b+KEVW+tRjtZ4glIZ9oPiDWY/8F0RMNYQgB+as6DWEsfJKKtVnCNAUyK79wopi+nqpkiPuCol5D5HisjU31tCIkA8w1teeW0N/qlwq9GxmG3MC5B3hewbPbX9kgZJU=
  - secure: KnXwz8SMEUK7bNV7ZiWN8sp9zYBw+oexo0CdX/xhjL2cZW0IWYmSh/PbH0RsSY5Jqpk3bMHyU6H2A2zdGUNlH89D99Ahux9bhsFzdie0gcMBRIDBwy8Tog9EaU+TS1whrD0uuroDPpb+eHCphIlOqFfX5Rm7ruKdmkFeY+6upuyBNM/vtpmichbbZeyMvIoKTFmgMWBZNapMIbH9fkwioFyKhYAWrXaiydJ/D9RtGgDlkieclMUM1YV/MyZcGQWeyuNrTzg88FFKnMgtCVYgbD5Hlalm9WqbDVmPvNgCx6e4aiA1s5KG7VP2VA9xISSSlv2hslf9gYqmijUd1xCYc7tm80jUaBSXyQ5IRBS4vso7iV8gvPvp2VgUcJ03sJm8VNq64T4+Jm3+Xmoc2/BgX3YJmTeOgPqu5jJ19TVJovAHUU7gHk8n0R24Swl9b6jftc8f/NLkPpJxYrXTDk0J5gtEpgKEWSW4gp8c/wMR6zVKd/6GoLXnDwzUKjCz/8A7sBEjGh+FoYIziWiF/8+QPf/mwSIqPofwDrhyVxAdtR9bMnXObmeZnkgtbxwQpvoOlr3JoU3F0Fooiv1nr4UYsS/GbXmuFzSWJlxQe6ieqyC8B5+rMyHxw/TcGaBUWXZh6DVAgi2WbxOwoW80FfKq0bk12emBjSZl+bF4nj6WtqU=
  - secure: CpnLlSEn8/43+PL++zf2wcuTlLP5Y1ZzdS8KVDUQo/p3ZVnOBIhALeoS5wcOrRAPs6HhaHKu2A1Xan9CJ9FZ/c630i0Ge8ZUT6/gyavaFjEk/GS+FGZbRX80JbJOPxQ6T+FvMGUGQCjqfXgl3XUGe4GSbweiErKIgKTPLHOoHlsi0qBAkf2WRtHTw+ZS5JccyvGjGMnfjERL61Ex3QNmGHWZDZGTQwCgyEm/DRtzvkG6gbYchLTFpnAk9/MCqFvuCO5hYrrPnjVD8cPsxK/HDmRtJ4cf1KKc9J9Ex+y10lC/2dHDQhvzztu9Ua2HMytOIAmjYYEtK5fDcOMYpE1/1Mo1cDLtg11oGJrzphcNBuMqpbgUfEMtnEyR++1SX3C1udUnoe3nd87g49vAxqdCla4rFMZANimr9LrCdkaZ0awp5GLu1oadjDk9BnvFNlTmuA+1CkntFeoK+N19xsN6z6ZTM63ho40sNwRb3hpiRlpkoT26b/93Hw3g+l0gGZHOYMZcerbI7+WO4yM8PFRfgRty4EQFSKesFdIA0VhM+ULKcxuYlVLojNoyskpqsgc3clus/LeOr9zlxrCaU5f6mQDuZUTHZms+qVAaFNeI8UCxcZGrNGJ7Za+o5gg8wJczzozyGkagJ6nNgMkPmXFanzwIkNdz8Sy8uJOf2F1zH/E=
install:
- nvm install 6.9.2 && npm install -g yarn && yarn global add tslint typescript
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.atomist"
deploy:
  provider: releases
  api_key:
    secure: TtuLbX/uYq3BSo4Ul+Xr0L3SfO8R+XI2N7B9SLffPMT4xEFUCO5gHV5XHTKLqFaWoV1YuqYRlrIssNLlXplIM/1fwDcykHTsBd9d4chlRGGshkHpKbcjPrMfAdWWNRP1ygqnuIGJFnUrFDXd3adBxMoojPUPZIhe1o0/6krFfxZ2P8LhUIZHIiznN1zrB6MtiWlGG55q2CLU7LzkqW+i8Fa6s7GIkVAvSujgLlv5NydP6gM4MlrtPAARGCrIGwEtqxbM/xeEGFhoZMBM+tFN+YVf2+20f8sAY+0hmIqcULR0S2WNYXY6VH33sTACONTREP84fdIYvPYHXo6uqmkIbUZMRdnrJc0rLM8mCBTa9acszaZhkwNCLStvuUPyy7IYGWvA9A0STdLE+LUmDhcU89MaRKp0O1hBVJmK20526csIsnNMCHY4oYLQ005sv3kyHDrRrbPQsAv844haeBLxDZitQZBv1mXxFGJloZrTCXN2SQhw0wen0up9E7iQBlQCIbTeezQqlWxg/HTQbCy1q8NNIr4lL/2eM40FAGGb/UXNnngMRSW/QduchumKa1iQ0wo0BB8rAcpRx8ixccCS8zShnzzEO4Hcwn2E+pEYH/bwZX8nTEFaPbxvPDdiqbcH9EqPiaF1bb+Ez2LaPh8oXcuhc3vuoWP3e7tGnx04Nu4=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
