dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: TRddBE5GyO27l2fh1H6RFRA2JBTWgBR0EsXDOdhamx6TEZV9iMxt2WETbQWTFJQth2zmt8HedvvF6ytQdClQqSCpvbThuc1HKqdXnjLHtF6dwlEQi/XoLOdaj8lksrg/Okz+GPRNzzVRW2qRrz06Xy1P4U0QYiTXbjb9p40SaEwPNAKMcmfPV07aG80wANmCUxeEHkgLvWQ13Eom6h30zXcOtFXboexjWbPHm0UTU+QyG1uvcilkJnI22YNpmB6K/0SgaNC75R55ZpxbbPovhIvEh0KyEDrdKUC+fLyfoCfcKQC+tDQEGRa8+juhehsDduQoXznj3om8usyyaTGw1fsVlDFqzW2oYHFv9OUWjcxiTrmSnT+rPlCMX6IMeeQzs0qPNL8lH/dzMLPfSYMl6uQPARWQFlM1lcdC4eO5tuaArrJl/5WWuh2sAtoLW6BcEGLGYa7yXMa5FRByvBhAODdQV0YztY8igJCCGZjA4NZMlcTY3O0RIk/dGjl5Dr8qzP6GI1RMv5rA4SZ156aIiXGWZnkOfdBfoUk7e4bizkL+zCFNhXtwqLlozEtw9HK4sk6fG6vH1yorE0CEvhnUeM235j0X7CIu6g7BsAVeIlSrDNXXov8R6idFDUkNe88N/NqoRpTb47mwcgSc8dpl1T7uzuVNcqKwf9ynELCAgbk=
  - secure: V4gx1HaUW5DPSG4x0LLRsJe+yOqNB0Cv8MSD3AhVi4wi4uP9yMYcxGk42D8OXOMB2eHe1cOAQKQ8UGj1vZLignwd5tJA8RAZRtgi73A7h/pVSuczDqzI2iHl+pgL5yXrT5FIQarbky3fBAjrXKxdwdBytpfOD95eVbLhmO//NSUSVUM7wxR8ji927d3YHrlAvhZIq6Ap1/jTf1qcbpLmmfAUBN9IZ6+qXcohRdXRTDKOy0pW7m7YcCxLCC02f2hzaw66CKmEKqTmm2k8j3xp2AU3OBD3HzjJglUu2i6FFYgNUhhBOABkm8dfp268qdTEWcmSbn7+OIpojcExnhAlpCS1OosMT/gnWVMUpK+7Yrr8sj4gyAcVX9HVuKqjzB8uImmQYFf4FgDQRJT0a3Gc6DuZF76m1mklsvO1qk9070lAixeF9+k7KX/4cdFwXsFBZhb3QoWTLYSTavYdwM746sIYmFKWbu5wKJiPdwQPLf2zTaefbn6LQedh/co20yZypD5jF+f320oslpJreHdQPtfqL/p8ZD6r0uNZcgdovYGRm1s4dgqP4IaMJbQLPBiKAQnfANAN4tuSc7t8xj0/y5q9JncU40R6I1al/hHln0lXK7An3i6h5IFg95lqH7+m6hjlAOrFERT+dFHCTREfj+qPYjkZYNvkWd1CI1E8FfA=
  - secure: D9A/dvpKT86/eBh8g3OJbtBcAA1nTJTeNgwgDD8EMF7CAv+Q0AMwU0uiLjywH9vUoSpAkjqBzmjTH7z+olyjSqXuxUSJSNtf0tsrLXFb+w+VoSOLwExHv0DL2BSLxH32+XaOwL1LIIe6BhT0moVsVrZfSLdE9JKJUL7mdRJFvXb5AHT4P1Jhkvy2JnzuigxIm73pcysu40oYX01hT2pUTpLc6OaZfDTlcnPJ5Lf4plr4D5Ss/y8S0QEdi6JsPSzyHFK9rd7rBXZZKNkHUwvjO+jYhlg2a8iuFWGDfL0vvxAT9tGIVxQPzuKmfu7G7VXm+r02FnAeuYKaY2Uy19xitq989IFOmS32QX76hqe0jFPf8DPkHptu6UkjKeGxxBezbdHLzyhWYW9hz/ClVvrfMvDfqjrZ3NdOUxjDmKItTAakX2VjDW2TYeeig9sGVCWNuQcWoH0NiHv3ZJjy0FdrM8T7CzSofVXEbuobHwNaM2oqW59Jz3B6VAFNGNn3hfkaNM4ib9Yg2+ppJ0HnFdIqpDWRNwIxNRh54CnBCHQRzpQAXSECRyPm8huwOQTwuVRomKtW2NZqYOfb7FxMkES1dT4z09r6ezIp52+mngFcStCQMc/lleuGV4p0WYVojrmD2XaAC/ZnRF8o80owUh9H0hedUvCo/yZUfTXjnbhAq/U=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.atomist"
